INSERT INTO product (PRODUCTID, ITEMNAME, DESCRIPTION, QUANTITY, QUANTITYINCARTS, PRICE, SPECIALPRICE) VALUES
(1, 'Dog Joint Supplement', 'A glucosamine and chondroitin supplement to support healthy joints in dogs.', 20, 0, 35, 0),
(2, 'Flea and Tick Preventive', 'A topical solution for preventing flea and tick infestations in dogs and cats.', 50, 0, 25, 20),
(3, 'Cat Dental Chews', 'Dental treats that help reduce tartar and freshen a cat''s breath.', 30, 0, 12, 0),
(4, 'Dog Shampoo for Sensitive Skin', 'A gentle, hypoallergenic shampoo designed for dogs with sensitive skin.', 15, 0, 15, 0),
(5, 'Prescription Dog Food', 'A veterinarian-prescribed diet designed for dogs with specific health conditions.', 10, 0, 70, 0),
(6, 'Cat Hairball Remedy', 'A gel supplement to help reduce hairball formation in cats.', 25, 0, 10, 8),
(7, 'Pet Ear Cleaner', 'A solution to clean and soothe pet ears, helping to prevent ear infections.', 40, 0, 14, 0),
(8, 'Puppy Training Pads', 'Absorbent pads designed to help with potty training puppies.', 100, 0, 30, 25),
(9, 'Dog Toothbrush and Toothpaste Set', 'A dental care set to maintain a dog''s oral hygiene.', 35, 0, 18, 0),
(10, 'Cat Scratching Post', 'A sturdy post designed to satisfy a cat''s natural scratching instinct.', 5, 0, 45, 0),
(11, 'Pet Weight Control Supplement', 'A supplement designed to help manage the weight of overweight pets.', 18, 0, 28, 0),
(12, 'Rehydration Electrolyte Solution', 'A solution to help pets recover from dehydration due to illness or heat.', 10, 0, 20, 0),
(13, 'Pet Calming Spray', 'A spray that helps reduce anxiety in pets during stressful situations.', 22, 0, 15, 12),
(14, 'Rabbit Hay Feeder', 'A feeder designed to hold hay, providing rabbits with a clean feeding area.', 12, 0, 25, 0),
(15, 'Bird Vitamin Drops', 'A liquid vitamin supplement to support the health of pet birds.', 30, 0, 9, 0),
(16, 'Pet First Aid Kit', 'A comprehensive kit containing bandages, antiseptic wipes, and other essentials for pet emergencies.', 8, 0, 40, 35),
(17, 'Dog Anxiety Vest', 'A vest that provides gentle pressure to help calm anxious dogs during stressful situations.', 10, 0, 45, 0),
(18, 'Reptile Calcium Powder', 'A calcium supplement powder for reptiles to ensure healthy bone development.', 15, 0, 12, 0),
(19, 'Fish Tank Water Conditioner', 'A solution that neutralizes harmful chemicals in tap water, making it safe for fish.', 20, 0, 8, 6),
(20, 'Pet Cooling Mat', 'A cooling mat designed to keep pets comfortable in hot weather.', 7, 0, 30, 0);
